### ISSUE TITLE
Ver carritos cerrados

### ISSUE THREAD

**Issue by fedesanches** [dds-frd-utn/2015-OristimGrails#10]
Hay que crear una vista donde se pueden ver todos los carritos que el usuario tiene cerrados para que pueda comprarlos.

Esta compra es simbólica, ya que no se va a implementar ningún medio de pago ni cosas por el estilo.

Una vez que "compra" el carrito con todos los artículos en el, este debería desaparecer de la lista de "carritos cerrados".

Estaria bueno, ya que el usuario ingresa un email cuando crea la cuenta, que se le mande uno diciendo algo como

> Muchas gracias por su compre. Id de compra "id_carrito". Saludos, el equipo de Oristim.

Pero esto es como para agregar alguna funcionalidad mas.

**Comment by martindegesus** [comment]
Lo veo poco viable
